// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	entity "github.com/OpenIoT-tools/OpenIoT/internal/core/models/entity"
	mock "github.com/stretchr/testify/mock"
)

// CategoryUseCase is an autogenerated mock type for the CategoryUseCase type
type CategoryUseCase struct {
	mock.Mock
}

type CategoryUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *CategoryUseCase) EXPECT() *CategoryUseCase_Expecter {
	return &CategoryUseCase_Expecter{mock: &_m.Mock}
}

// CreateCategory provides a mock function with given fields: category
func (_m *CategoryUseCase) CreateCategory(category *entity.Category) (*entity.Category, error) {
	ret := _m.Called(category)

	if len(ret) == 0 {
		panic("no return value specified for CreateCategory")
	}

	var r0 *entity.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.Category) (*entity.Category, error)); ok {
		return rf(category)
	}
	if rf, ok := ret.Get(0).(func(*entity.Category) *entity.Category); ok {
		r0 = rf(category)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.Category) error); ok {
		r1 = rf(category)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CategoryUseCase_CreateCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCategory'
type CategoryUseCase_CreateCategory_Call struct {
	*mock.Call
}

// CreateCategory is a helper method to define mock.On call
//   - category *entity.Category
func (_e *CategoryUseCase_Expecter) CreateCategory(category interface{}) *CategoryUseCase_CreateCategory_Call {
	return &CategoryUseCase_CreateCategory_Call{Call: _e.mock.On("CreateCategory", category)}
}

func (_c *CategoryUseCase_CreateCategory_Call) Run(run func(category *entity.Category)) *CategoryUseCase_CreateCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.Category))
	})
	return _c
}

func (_c *CategoryUseCase_CreateCategory_Call) Return(_a0 *entity.Category, _a1 error) *CategoryUseCase_CreateCategory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CategoryUseCase_CreateCategory_Call) RunAndReturn(run func(*entity.Category) (*entity.Category, error)) *CategoryUseCase_CreateCategory_Call {
	_c.Call.Return(run)
	return _c
}

// ListCategories provides a mock function with no fields
func (_m *CategoryUseCase) ListCategories() ([]*entity.Category, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListCategories")
	}

	var r0 []*entity.Category
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*entity.Category, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*entity.Category); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Category)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CategoryUseCase_ListCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCategories'
type CategoryUseCase_ListCategories_Call struct {
	*mock.Call
}

// ListCategories is a helper method to define mock.On call
func (_e *CategoryUseCase_Expecter) ListCategories() *CategoryUseCase_ListCategories_Call {
	return &CategoryUseCase_ListCategories_Call{Call: _e.mock.On("ListCategories")}
}

func (_c *CategoryUseCase_ListCategories_Call) Run(run func()) *CategoryUseCase_ListCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CategoryUseCase_ListCategories_Call) Return(_a0 []*entity.Category, _a1 error) *CategoryUseCase_ListCategories_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CategoryUseCase_ListCategories_Call) RunAndReturn(run func() ([]*entity.Category, error)) *CategoryUseCase_ListCategories_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveCategory provides a mock function with given fields: categoryId
func (_m *CategoryUseCase) RemoveCategory(categoryId string) error {
	ret := _m.Called(categoryId)

	if len(ret) == 0 {
		panic("no return value specified for RemoveCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(categoryId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CategoryUseCase_RemoveCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveCategory'
type CategoryUseCase_RemoveCategory_Call struct {
	*mock.Call
}

// RemoveCategory is a helper method to define mock.On call
//   - categoryId string
func (_e *CategoryUseCase_Expecter) RemoveCategory(categoryId interface{}) *CategoryUseCase_RemoveCategory_Call {
	return &CategoryUseCase_RemoveCategory_Call{Call: _e.mock.On("RemoveCategory", categoryId)}
}

func (_c *CategoryUseCase_RemoveCategory_Call) Run(run func(categoryId string)) *CategoryUseCase_RemoveCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *CategoryUseCase_RemoveCategory_Call) Return(_a0 error) *CategoryUseCase_RemoveCategory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CategoryUseCase_RemoveCategory_Call) RunAndReturn(run func(string) error) *CategoryUseCase_RemoveCategory_Call {
	_c.Call.Return(run)
	return _c
}

// NewCategoryUseCase creates a new instance of CategoryUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoryUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoryUseCase {
	mock := &CategoryUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
